import { precacheAndRoute, createHandlerBoundToURL, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle navigation requests
registerRoute(
  new NavigationRoute(
    createHandlerBoundToURL('index.html'),
    {
      allowlist: [
        /^\/$/,  // root path
        /^\/auth\/callback/,  // auth callback
        /^\/signin/,  // signin page
        /^\/signup/,  // signup page
        /^\/onboarding/,  // onboarding page
        /^\/home/,  // home page
        /^\/stats/  // stats page
      ]
    }
  )
);

// Cache Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 31536000 // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  }),
  'GET'
); 